services:
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER:
      MYSQL_PASSWORD: 
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  adminer:
    image: adminer:latest
    container_name: laravel_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
